sudo: false
# cache: pip
language: python
python:
- "3.6"
- "3.5"
- "2.7"
env:
- REQ="Django>=1.11,<2.0"
- REQ="Django>=2.0,<2.1"
- REQ="Django>=2.1,<2.2"
- REQ="https://github.com/django/django/archive/master.zip#egg=Django"
matrix:
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
  exclude:
    - python: "2.7"
      env: REQ="Django>=2.0,<2.1"
    - python: "2.7"
      env: REQ="Django>=2.1,<2.2"
    - python: "2.7"
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
install:
- pip install -U pip wheel
- pip install Pillow>5.4.0
- pip install $REQ
- python setup.py install
script: cd tests && ./manage.py test testapp -v 2 && cd ..

jobs:
  include:
    - stage: prehistoric
      python: "2.7"
      env: REQ="Django>=1.8,<1.9"
    - stage: style
      env: REQ=none
      install: skip
      script:
        - pip install black flake8
        - flake8 .
        - black --check imagefield tests
